### ISSUE TITLE
Ability to surpress a check failure.

### ISSUE THREAD

**Issue by rowanc1** [curvenote/curvenote#517]
Check comes back with:

```
{
  id: 'doi',
  key: 'jupyter',
  status: 'failure',
}
```

Add to curvenote.yml(?)
```
checks:
  skip:
    - doi:
        - jupyter
```
or skip all the doi checks (or all of another kind of check that maybe doesn’t have a key):

```
checks:
  skip:
    - doi
```
