### ISSUE TITLE
`curvenote` missing a `myst build --all` equivalent

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/curvenote#547]
So in `myst` we can run `muyst build --all` and all exports will build, there is no equivalent in `curvenote`. 

In curvenote the cli is setup to as `curvenote exports <cmd>` which we could live with but it is missing a simple `curvenote exports --all`.

The use case I have is I am wanting to simply verify the build of a computational article prior to submitting it. The article is setup like:

```
project:
  ...
  jupyter: true
  exports:
    - format: meca
  requirements:
    - requirements.txt
    - apt.txt
  resources:
    - src/**/*
    - example.csv
    - model.pkl
```

and I want to be able to run `curvenote build|exports --all` to just ensure that everything builds and in this case that i get a `meca` archive out or it. `myst build --all` works in this case but if I run `curvenote exports meca`, which I the closest command I can find, I get an error as I have to spec the article, and probably export, where I want to just build a meca file.

Can we add an `curvenote exports --all` option?
should we do more to align `curvenote build|export` with  with `myst build`?
